package it.unisa.orarilavoro;

public class DatabaseStrings {
    public static final String FIELD_ID = "_id";
    public static final String FIELD_GIORNO = "giorno";
    public static final String FIELD_MESE = "mese";
    public static final String FIELD_ANNO = "anno";
    public static final String FIELD_DA_ORA = "da_ora";
    public static final String FIELD_DA_MINUTO = "da_minuto";
    public static final String FIELD_A_ORA = "a_ora";
    public static final String FIELD_A_MINUTO = "a_minuto";
    public static final String FIELD_ORE_TOTALI = "ore_totali";
    public static final String FIELD_MINUTI_TOTALI = "minuti_totali";
    public static final String FIELD_NOME = "nome";
    public static final String FIELD_ORA_INIZIO = "ora_inizio";
    public static final String FIELD_ORA_FINE = "ora_fine";
    public static final String FIELD_ORE_PAUSA = "ore_pausa";
    public static final String FIELD_ORA_INIZIO_L = "ora_inizio_l";
    public static final String FIELD_ORA_FINE_L = "ora_fine_l";
    public static final String FIELD_ORE_PAUSA_L = "ore_pausa_l";
    public static final String FIELD_ORA_INIZIO_M = "ora_inizio_m";
    public static final String FIELD_ORA_FINE_M = "ora_fine_m";
    public static final String FIELD_ORE_PAUSA_M = "ore_pausa_m";
    public static final String FIELD_ORA_INIZIO_ME = "ora_inizio_me";
    public static final String FIELD_ORA_FINE_ME = "ora_fine_me";
    public static final String FIELD_ORE_PAUSA_ME = "ore_pausa_me";
    public static final String FIELD_ORA_INIZIO_G = "ora_inizio_g";
    public static final String FIELD_ORA_FINE_G = "ora_fine_g";
    public static final String FIELD_ORE_PAUSA_G = "ore_pausa_g";
    public static final String FIELD_ORA_INIZIO_V = "ora_inizio_v";
    public static final String FIELD_ORA_FINE_V = "ora_fine_v";
    public static final String FIELD_ORE_PAUSA_V = "ore_pausa_v";
    public static final String FIELD_ORA_INIZIO_S = "ora_inizio_s";
    public static final String FIELD_ORA_FINE_S = "ora_fine_s";
    public static final String FIELD_ORE_PAUSA_S = "ore_pausa_s";
    public static final String FIELD_ORA_INIZIO_D = "ora_inizio_d";
    public static final String FIELD_ORA_FINE_D = "ora_fine_d";
    public static final String FIELD_ORE_PAUSA_D = "ore_pausa_d";
    public static final String FIELD_RICHIESTA_NOTIFICA = "richiesta_notifica";
    public static final String FIELD_ORA_NOTIFICA = "ora_notifica";
    public static final String FIELD_MINUTI_NOTIFICA = "minuti_notifica";
    public static final String TBL_NAME = "Orario";
    public static final String TBL_NAME_IMPOSTAZIONI = "Impostazioni";
}
